%-----------------------------------------------------------------------
% Random Cascade Simulator
%-----------------------------------------------------------------------
function [pfield1] = randomcascadefun(varargin)
%-----------------------------------------------------------------------
%-----------------------------------------------------------------------
%
% Syntax:
%
%       randomcascadefun(pfield0,Nsta,Nsim)
%
% Description:
%
%    This function is designed to compute a random-cascade field using 
%    a two-state model for the cascade generator, a branching number of 
%    four, and a coarse-scale precipitation field. To utilize this 
%    function, the coarse-scale precipitation field, the number of 
%    stages to be generated by the multiplicative process, and the 
%    number of simulations are required.
%
%
% Input arguments:
%
%    pfield0:  Coarse-scale precipitation field.
%    Nsta:     Number of stages in the multiplicative process.
%    Nsim:     Number of realizations of the random cascade model.
%
% Output arguments:
%
%    pfield1:  Simulated random-cascade field.
%
% Last update: June 18, 2026
% Authors: 
%      Victor Penaranda-Velez (victor.penaranda[at]atmosfera.unam.mx)
%
%-----------------------------------------------------------------------
%-----------------------------------------------------------------------

if nargin==3

    % Variables
    
    pfield0 = varargin{1}; % Source field
    
    Nsta = varargin{2};      % Number of stage in the random cascade
    
    Nsim = varargin{1};      % Number of realizations
    
    % Fractal dimension of the source field
    
    [n,r] = boxcount(pfield0); % Moisy's algorithm
    
    P = polyfit(log(r),log(n),1);
    
    DF = -P(1); % Fractal Dimension
    
    % Codimension of the source field
    
    codi = 2 - DF;
    
    % Parameter estimation of the cascade generator
    
    branch = 4; % Branching number
    
    funobj = @(x) abs(mean(reshape(generator(codi,x(1),x(2)),1,branch))-1);
    
    x0 = [3.2,-0.7];
    
    x = fminsearch(funobj,x0);
    
    gammaless = x(1);
    
    gammaplus = x(2);
    
    % Random Cascade Field Simulation
    
    for sim = 1:Nsim
    
        M = pfield0;
        
        for k = 1:Nsta
        
            N = zeros(size(pfield0,1)*2^k,size(pfield0,1)*2^k);
        
            for ii = 1:size(M,1)
        
                for jj = 1:size(M,1)
                
                    N(2*(ii-1)+1:2*ii,2*(jj-1)+1:2*jj) = M(ii,jj);
                    
                    N(2*(ii-1)+1:2*ii,2*(jj-1)+1:2*jj) = N(2*(ii-1)+1:2*ii,2*(jj-1)+1:2*jj).*...
                                                           generator(codi,gammaless,gammaplus);
                    
                end
        
            end
        
            M = N;
            
            clearvars N
            
        end
        
        if sim==1; 
            
            pfield1 = M;
    
        else
    
            pfield1 = pfield1 + M;
    
        end
    
    end
    
    pfield1 = pfield1/Nsim; % Averaged field

else

    error('Incorrect number of input variables')

end

%-----------------------------------------------------------------------
%-----------------------------------------------------------------------
